# Generic Parameters
threshold: 0.3
force_dag: False
batch_size: 64
max_epochs: 7000
early_stop: True
# DAGMA Custom Parameters
learning_rate:
  loguniform: [1.e-4, 1.e-3]
lambda_reg:
  loguniform: [0.0001, 0.1]
hidden_size: [10]
initial_path_coefficient: 1.0
path_decay_factor: 0.1
log_det_parameter: [1., 1., 1., 1.]
max_steps: 4