# Generic Parameters
threshold: 0.3
force_dag: False
batch_size: 64
max_epochs: 5000
early_stop: True
# NOCURL Custom Parameters
learning_rate:
  loguniform: [1.e-4, 1.e-3]
lambda_reg:
  loguniform: [0.0001, 0.1]
multiplier: []
prethreshold: 0.3
compute_weights: False
joint_learn: True
progress_rate: 0.25