# Generic Parameters
threshold: 0.3
force_dag: False
batch_size: 64
max_epochs: 5000
early_stop: True
# NOTEARS Custom Parameters
learning_rate:
  loguniform: [1.e-4, 1.e-3]
lambda_reg:
  loguniform: [0.0001, 0.1]
hidden_size: null
init_penalty: 1.0
penalty_fact: 10.0
max_penalty: 1.e+16
multiplier: 1.0
dagness_tol: 1.e-8
progress_rate: 0.25
max_iter: 100
